export const webinarSamples = [
  {
    id: 1,
    instructorName: "Alice Johnson",
    instructorRole: "Senior Developer",
    instructorImage: "https://i.postimg.cc/Jh8vpP09/image.png",
    instructorCompany: "Tech Solutions",
    topics: "Front End Engineering",
    webinarTitle: "Building Modern Web Applications",
    webinarStartDate: "2024-09-20",
    startTime: "10:00",
    endTime: "12:00",
  },
  {
    id: 2,
    instructorName: "Bob Smith",
    instructorRole: "Data Scientist",
    instructorImage: "https://i.postimg.cc/Jh8vpP09/image.png",
    instructorCompany: "DataCorp",
    topics: "Front End Engineering",
    webinarTitle: "Introduction to Machine Learning",
    webinarStartDate: "2024-09-21",
    startTime: "02:00",
    endTime: "04:00",
  },
  {
    id: 3,
    instructorName: "Clara Lee",
    instructorRole: "UX Designer",
    instructorImage: "https://i.postimg.cc/Jh8vpP09/image.png",
    instructorCompany: "Creative Designs",
    topics: "DevOps Engineering",
    webinarTitle: "Designing User-Centered Experiences is Very Long Title",
    webinarStartDate: "2024-09-22",
    startTime: "09:00",
    endTime: "11:00",
  },
  {
    id: 4,
    instructorName: "David Kim",
    instructorRole: "Cloud Architect",
    instructorImage: "https://i.postimg.cc/Jh8vpP09/image.png",
    instructorCompany: "Cloudify Inc.",
    topics: "Careers",
    webinarTitle: "Mastering Cloud Infrastructure",
    webinarStartDate: "2024-09-23",
    startTime: "03:00",
    endTime: "05:00",
  },
  {
    id: 5,
    instructorName: "Ella Brown",
    instructorRole: "Cybersecurity Expert",
    instructorImage: "https://i.postimg.cc/Jh8vpP09/image.png",
    instructorCompany: "SecureTech",
    topics: "Front End Engineering",
    webinarTitle: "Protecting Your Digital Assets",
    webinarStartDate: "2024-09-24",
    startTime: "11:00",
    endTime: "01:00",
  },
  {
    id: 6,
    instructorName: "Frank White",
    instructorRole: "AI Researcher",
    instructorImage: "https://i.postimg.cc/Jh8vpP09/image.png",
    instructorCompany: "AI Innovations",
    topics: "Front End Engineering",
    webinarTitle: "AI for Beginners",
    webinarStartDate: "2024-09-25",
    startTime: "01:00",
    endTime: "03:00",
  },
  {
    id: 7,
    instructorName: "Grace Hill",
    instructorRole: "Marketing Strategist",
    instructorImage: "https://i.postimg.cc/Jh8vpP09/image.png",
    instructorCompany: "MarketMasters",
    topics: "Front End Engineering",
    webinarTitle: "Mastering Digital Marketing",
    webinarStartDate: "2024-09-26",
    startTime: "04:00",
    endTime: "06:00",
  },
  {
    id: 8,
    instructorName: "Henry Jones",
    instructorRole: "Full Stack Developer",
    instructorImage: "https://i.postimg.cc/Jh8vpP09/image.png",
    instructorCompany: "DevWorks",
    topics: "Front End Engineering",
    webinarTitle: "Become a Full Stack Developer",
    webinarStartDate: "2024-09-27",
    startTime: "12:00",
    endTime: "02:00",
  },
  {
    id: 9,
    instructorName: "Irene Green",
    instructorRole: "Project Manager",
    instructorImage: "https://i.postimg.cc/Jh8vpP09/image.png",
    instructorCompany: "PM Solutions",
    topics: "Careers",
    webinarTitle: "Managing Projects with Agile is a Very Long name",
    webinarStartDate: "2024-09-28",
    startTime: "02:00",
    endTime: "04:00",
  },
  {
    id: 10,
    instructorName: "James Carter",
    instructorRole: "DevOps Engineer",
    instructorImage: "https://i.postimg.cc/Jh8vpP09/image.png",
    instructorCompany: "DevOps Hub",
    topics: "Front End Engineering",
    webinarTitle: "Introduction to DevOps",
    webinarStartDate: "2024-09-29",
    startTime: "05:00",
    endTime: "07:00",
  },
];

export const colors = [
  "#741DE3",
  "#E72174",
  "#08A79E",
  "#0E51F1",
  "#FFB023",
  "#088761",
];
